"""Update User model for usdt_public_key

Revision ID: 1a24ae6654df
Revises: 24795ada219e
Create Date: 2024-12-09 14:15:24.927242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a24ae6654df'
down_revision = '24795ada219e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usdt_public_key', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_column('usdt_public_key')

    # ### end Alembic commands ###
